### ISSUE TITLE
Hide "root" in  the viewer

### ISSUE THREAD

**Issue by Nebulis** [gjj/opencerts-privacy-filter#6]
I'm wondering if the word might be troublesome for people to understand (where is this "root" from ?). I would recommend to get rid of it :)

**Comment by gjj** [comment]
shifted from JSON tree to flattened JSON format in #18 & table only shows everything within `data`. no more `root`.

**Comment by Nebulis** [comment]
can you open an issue to actually add a json viewer ? ( so that can display on different format), wdyt ?
